apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
  project: default
  source:
    path: components/argo-events/resources
    repoURL: https://github.com/roi-codefresh/csdp-official-runtime.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
