apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/codefresh-io/argo-events/csdp-official-v0.0.1/manifests/install.yaml
  - https://raw.githubusercontent.com/codefresh-io/argo-events/csdp-official-v0.0.1/manifests/install-validating-webhook.yaml
  - eventbus.yaml
